name: Update Trophies

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *' # 每隔12个小时执行一次

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      PSN_COOKIE: ${{ secrets.PSN_COOKIE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.18.0'

      - name: Install dependencies
        run: npm install

      - name: Get trophies
        run: |
          data=$(node ./script/getTrophies.js)
          echo $data  > trophies.json

      - name: Commit and push changes
        run: |
          git config --global user.name ${{ secrets.GH_USER_NAME }}
          git config --global user.email ${{ secrets.GH_USER_EMAIL }}
          git add .
          git commit -m "Update trophies"
          git push
